version: '3.8'

services:
  architect-plus:
    build: .
    ports:
      - "3000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=10).raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
